ForceUpdate: false
MetricMethod: Haversine
DistanceThreshold: 1000.0
DatasetDirectory: C:\Users\LeeLemay\Documents\Projects\Python\tkinter_gui\data
RecentDirectories:
- C:\Users\LeeLemay\Documents\Projects\Python\tkinter_gui\data
- C:\Users\LeeLemay\Documents\Projects\Python\tkinter_gui\logs
